name = "debsmikle"
author = "JBMagination"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64551940b4afa298288518253422819b066014f7f09cb9c3f5610e9986e17df3"

[versions]
fabric = "0.14.8"
minecraft = "1.19.1"
